<a href="https://colab.research.google.com/github/phamkevinT/tensorflow_practice/blob/main/tensorflow_fundamentals/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamentals of TensorFlow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (way to speed up Python functions)
* Using GPUs with TensorFlow

## Introduction to Tensors

In [30]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [31]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [32]:
# Check number of dimensions of a tensor
scalar.ndim

0

In [33]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [34]:
# Check the dimension of our vector
vector.ndim

1

In [35]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [36]:
matrix.ndim

2

In [37]:
# Creating another matrix
matrix_2 = tf.constant([[10., 7,],
                        [3., 2.],
                        [8., 9.]], dtype=tf.float16)

In [38]:
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [39]:
matrix_2.ndim

2

In [40]:
# Creating a tensor
tensor = tf.constant([  [[1, 2, 3],
                         [4, 5, 6]],
                      
                        [[7, 8, 9],
                         [10, 11, 12]], 
                      
                        [[13, 14, 15],
                         [16, 17, 18]] ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [41]:
tensor.ndim

3

Recap:

* Scalar: a single number, (0-dimensional tensor)
* Vector: a number with direction (ex. wind speed and direction), (1-dimensional tensor)
* Matrix: a 2-dimensional array of numbers, (2-dimensional tensor)
* Tensor: a n-dimensional array of numbers

## Creating tensors with tf.Variable

In [42]:
# Create the same tensor with tf.Variable() as above
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor = tf.Variable([10, 7])

unchangeable_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [43]:
# Changing one of the elements in changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensors


In [44]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

## Shuffle order of elements in a tensor

* Shuffle data so inherit order doesn't affect the model learning

In [45]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle the tensor
shuffled = tf.random.shuffle(not_shuffled)

In [46]:
not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 2,  5],
        [10,  7]], dtype=int32)>)

If we want our shuffled tensors to be in the same order, use the global level random seed & operation level random seed

In [47]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=42) # Operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [48]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [49]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

NumPy arrays vs TensorFlow Tensors:
* Tensors can be run on a GPU (much faster for numerical computing)

In [50]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

# X = tf.constant(matrix) # uppercase variable name for matrix or tensor
# y = tf.constant(vector) # lowwercase variable name for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [51]:
# Turning NumPy array into tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [52]:
# Reshaping tensor 
B = tf.constant(numpy_A, shape=(2, 3, 4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

* Shape - length (number of elements) of each dimension of a tensor 
  - tensor.shape
* Rank - number of tensor dimensions 
  - tensor.ndim
* Axis / Dimension - a particular dimension of a tensor 
  - tensor[0]
* Size - total number of items in the tensor 
  - tf.size(tensor)

In [53]:
from tensorflow.python.ops.gen_array_ops import rank
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [55]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [56]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in tensor: 120


## Indexing tensors

Tensors can be indexed just like Python lists

In [57]:
# Get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [58]:
# Get the first element each dimension from each index except final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [59]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [60]:
# Get the last item of each row of the rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [61]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [62]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" to expand the final/last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [63]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

**Basic Operations**

Addition, Subtraction, Multiplication, Division

In [64]:
# Add values to tensor element
tensor = tf.constant([[10, 7],
                      [3, 4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [65]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [66]:
# Multiplication 
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [67]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [68]:
# Division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [69]:
# Alternatively, use tensorflow built-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication

In [70]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [71]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [72]:
# Different shape tensors

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [73]:
# Cannot perform matrix multiplication because inner dimension don't match .... have to reshape
# Have to reshape X to (2,3) -> (2,3) @ (3,2)
# OR reshape y to (3,2) -> (3,2) @ (2,3)

# Option 1 - tf.reshape()
# Option 2 - tf.transpose()

# Option 1 example of reshape y from (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [74]:
# Matrix multiplication with reshaped y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [75]:
# Option 2 example of reshape X from (3, 2) to (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [76]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [77]:
# Achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## Multiplying matrices by each other is also referred to as the dot product.

Note that although using both reshape and tranpose work, you get different results when using each

In [78]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [79]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

The outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

* tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).

* tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

## Changing datatype of a tensor

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

Change the datatype of a tensor using tf.cast()

In [80]:
# Tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Tensor with default datatype (int32)
C = tf.constant([1, 7])

B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [81]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [82]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Get absolute value - tf.abs()

In [83]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [84]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Tensor Aggregation - min, max, mean, sum 

Aggregation methods
* tf.reduce_min() - minimum value in a tensor
* tf.reduce_max() - maximum value in a tensor (helpful for when you want to find the highest prediction probability)
* tf.reduce_mean() - mean of all elements in a tensor
* tf.reduce_sum() - sum of all elements in a tensor
* tf.reduce_std() - standard deviation
* tf.reduce_variance() - variance

Note: Full module tf.math.reduce_min() but you can use the alias tf.reduce_min()

In [85]:
# Tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([14,  0, 43,  0, 59, 17, 22, 94, 69, 15, 11, 32, 77, 78, 35, 33, 65,
       52, 96, 32, 61, 53, 18,  5, 28, 80, 50, 96, 65, 48, 51,  6, 17, 53,
        0, 63, 61, 44, 42, 78, 57, 18, 55, 78, 84, 17, 75, 37, 74, 82])>

In [86]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [87]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [88]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [89]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2340>

## Finding the positional maximum and minimum

* tf.argmax() - the position of the maximum element in a given tensor
* tf.argmin() - the position of the minimum element in a given tensor

In [90]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.04064879, 0.196486  , 0.79056671, 0.46600811, 0.43167547,
       0.2477405 , 0.21988767, 0.87772029, 0.92708989, 0.25918197,
       0.93039016, 0.64516334, 0.24194237, 0.90628736, 0.03615553,
       0.98811016, 0.98161101, 0.79597784, 0.62318443, 0.17717523,
       0.41881676, 0.98596581, 0.45284234, 0.26992205, 0.99609309,
       0.13041858, 0.59923703, 0.28462672, 0.02581984, 0.49049287,
       0.93644811, 0.08461209, 0.31854779, 0.30001924, 0.82311504,
       0.71998552, 0.53283874, 0.74527955, 0.5713843 , 0.67520478,
       0.89222469, 0.41405406, 0.08026542, 0.43878433, 0.07494594,
       0.79972623, 0.24645027, 0.72342103, 0.2892112 , 0.76927681])>

In [91]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [92]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [93]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Getting element from F using the argmax position: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 24
The maximum value of F is: 0.9960930871392352
Getting element from F using the argmax position: 0.9960930871392352
Are the two max values the same (they should be)? True


# Squeezing a tensor (removing all single dimensions)
* tf.squeeze() - remove all dimensions of 1 from a tensor

In [94]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [95]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[91, 94, 11,  9, 25, 65, 64, 58,  4, 16, 16, 28, 22, 71, 10,
           31, 74, 16, 97, 48, 66, 79, 57, 69, 11, 66, 19, 27, 11, 32,
            3, 86,  3,  9, 51,  3, 98, 86, 85, 73, 39, 94,  3, 32, 79,
           16, 82, 38, 53, 43]]]]])>

In [96]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

## One-Hot Encoding
* Converting categorical data so that it can be provided to machine learning algorithms
* tf.one_hot()
* Specify the *depth* parameter (the level which you want to one-hot encode to)

In [97]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [98]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="Live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Live!', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'Live!', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'Live!', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'Live!']], dtype=object)>

# Square, log, square root

* tf.square() - get the square of every value in a tensor.
* tf.sqrt() - get the square-root of every value in a tensor (elements need to be floats).
* tf.math.log() - get the natural log of every value in a tensor (elements need to be floats).

In [99]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [100]:

# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [101]:
# Square-root
# Change tensor H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [102]:
# Find the square-root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [103]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manipulating tf.Variable tensors

Tensors created with tf.Variable() can be changed in place using methods such as:

* .assign() - assign a different value to a particular index of a variable tensor.
* .add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [104]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [105]:
# Change last element to 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [106]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and NumPy

Tensors can also be converted to NumPy arrays using:

* np.array() - pass a tensor to convert to an ndarray 
* tensor.numpy() - call on a tensor to convert to an ndarray

Note: TensorFlow tensors can be run on GPU for faster numerical processing

In [107]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [108]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [109]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)


By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

In [110]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPUs

In [111]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [112]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


## Additional Exercises


In [113]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]]])

In [114]:
# 2. Find the shape, rank and size of the tensors you created in 1.
tensor.shape

TensorShape([1, 2, 3])

In [115]:
tensor.ndim

3

In [116]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [117]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
random_ten_1 = tf.random.Generator.from_seed(42)
random_ten_1 = random_ten_1.normal(shape=(5, 300))

random_ten_2 = tf.random.Generator.from_seed(42)
random_ten_2 = random_ten_2.normal(shape=(5, 300))

In [118]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.transpose(random_ten_1)

<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.88051033, -1.5306779 ,  0.84324265,  0.04888754],
       [-0.06854702, -0.32426047, -0.8620293 , -0.23379943, -0.66408694],
       [ 0.07595026, -2.4847078 , -0.16359143,  0.4276398 , -1.787366  ],
       ...,
       [-1.0718341 ,  0.16512105,  0.34288087, -1.0428714 ,  0.1947453 ],
       [-1.0722276 ,  1.155565  ,  1.2167931 , -0.73970354,  0.5656089 ],
       [-0.00586287, -0.10707551, -1.24293   ,  0.0177109 ,  0.18439198]],
      dtype=float32)>

In [119]:
tf.matmul(tf.transpose(random_ten_1), random_ten_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[ 4.404135  ,  1.42725   ,  2.6539783 , ..., -0.72917545,
        -2.6648772 ,  2.0251913 ],
       [ 1.42725   ,  1.3486117 ,  2.0284915 , ..., -0.16114965,
        -1.5527885 ,  0.97997123],
       [ 2.6539783 ,  2.0284915 ,  9.583857  , ..., -1.3418305 ,
        -4.479011  ,  0.14693668],
       ...,
       [-0.72917545, -0.16114965, -1.3418305 , ...,  2.4191668 ,
         2.6388385 , -0.42013407],
       [-2.6648772 , -1.5527885 , -4.479011  , ...,  2.6388385 ,
         4.8326626 , -1.5386422 ],
       [ 2.0251913 ,  0.97997123,  0.14693668, ..., -0.42013407,
        -1.5386422 ,  1.5906887 ]], dtype=float32)>

In [120]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tf.transpose(random_ten_1), random_ten_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[ 4.404135  ,  1.42725   ,  2.6539783 , ..., -0.72917545,
        -2.6648772 ,  2.0251913 ],
       [ 1.42725   ,  1.3486117 ,  2.0284915 , ..., -0.16114965,
        -1.5527885 ,  0.97997123],
       [ 2.6539783 ,  2.0284915 ,  9.583857  , ..., -1.3418305 ,
        -4.479011  ,  0.14693668],
       ...,
       [-0.72917545, -0.16114965, -1.3418305 , ...,  2.4191668 ,
         2.6388385 , -0.42013407],
       [-2.6648772 , -1.5527885 , -4.479011  , ...,  2.6388385 ,
         4.8326626 , -1.5386422 ],
       [ 2.0251913 ,  0.97997123,  0.14693668, ..., -0.42013407,
        -1.5386422 ,  1.5906887 ]], dtype=float32)>

In [121]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
random_ten_3 = tf.random.Generator.from_seed(42)
random_ten_3 = random_ten_3.normal(shape=(224, 224, 3))

In [122]:
# 7. Find the min and max values of the tensor you created in 6.

tf.reduce_min(random_ten_3), tf.reduce_max(random_ten_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>)

In [123]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
random_ten_4 = tf.random.Generator.from_seed(42)
random_ten_4 = random_ten_4.normal(shape=(1, 224, 224, 3))

In [124]:
random_ten_squeezed = tf.squeeze(random_ten_4)
random_ten_squeezed.shape, random_ten_squeezed.ndim

(TensorShape([224, 224, 3]), 3)

In [137]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
ten_ten = tf.constant(np.arange(10, 20))
ten_ten

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [138]:
print(f"Index with max value:", tf.argmax(ten_ten).numpy())

Index with max value: 9


In [143]:
# 10. One-hot encode the tensor you created in 9.
tf.one_hot(ten_ten, depth=20)

<tf.Tensor: shape=(10, 20), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     